locale: en-GB
site_theme: default
title: Forrest Cheung, PhD
title_separator: '-'
name: Forrest Cheung
description: 'Forrest Cheung personal academic website'
url: https://forrestcheungtw.github.io
baseurl: ''
repository: https://forrestcheungtw.github.io/
author:
  avatar: profile.png
  name: Forrest TW Cheung
  pronouns:
  bio: Sleep Scientist
  location: Oxford, United Kingdom
  employer: University of Oxford
  uri: https://www.ndcn.ox.ac.uk/team/forrest-tin-wai-cheung
  email: forrestcheungtw@gmail.com
  academia:
  arxiv:
  googlescholar: https://scholar.google.com/citations?user=67fQKaUAAAAJ&hl
  inspire-hep:
  impactstory:
  orcid: https://orcid.org/0000-0003-4462-9639
  semantic:
  pubmed:
  researchgate: https://www.researchgate.net/profile/Forrest-Cheung
  scopus:
  bitbucket:
  codepen:
  dribbble:
  github:
  kaggle:
  stackoverflow:
  artstation:
  bluesky:
  facebook:
  flickr:
  foursquare:
  goodreads:
  google_plus:
  keybase:
  instagram:
  lastfm:
  linkedin:
  mastodon:
  medium:
  pinterest:
  soundcloud:
  steam:
  telegram:
  tumblr:
  twitter:
  vine:
  weibo:
  wikipedia:
  xing:
  youtube:
  zhihu:
publication_category:
  books:
    title: Books
  manuscripts:
    title: Journal Articles
  conferences:
    title: Conference Papers
teaser:
breadcrumbs: true
words_per_minute: 160
future: true
read_more: disabled
talkmap_link: false
comments:
  provider:
  disqus:
    shortname:
  discourse:
    server:
  facebook:
    appid:
    num_posts:
    colorscheme:
staticman:
  allowedFields:
    - name
    - email
    - url
    - message
  branch: gh-pages
  commitMessage: New comment.
  filename: comment-{@timestamp}
  format: yml
  moderation: true
  path: _data/comments/{options.slug}
  requiredFields:
    - name
    - email
    - message
  transforms:
    email: md5
  generatedFields:
    date:
      type: date
      options:
        format: iso8601
atom_feed:
  hide: false
  path:
google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:
twitter:
  username:
facebook:
  username:
  app_id:
  publisher:
og_image:
og_description:
social:
  type:
  name:
  links:
analytics:
  provider: 'false'
  google:
    tracking_id:
include:
  - .htaccess
  - _pages
  - files
exclude:
  - '*.sublime-project'
  - '*.sublime-workspace'
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: |+


incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ''
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ''
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ''
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ''
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ''
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
timezone: Etc/UTC
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
compress_html:
  clippings: all
  ignore:
    envs: development
